spring.application.name=resume-screening-system

spring.datasource.url=jdbc:mysql://localhost:3306/resume_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thawarigajanan714@gmail.com
spring.mail.password=tmtv lhzd jmbf whby

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true



spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=tinyllama



